Index/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('otp/', views.otp, name='otp'),
]

urlpatterns += [
    re_path(r'^accounts/', views.obligatory, name="obligatory"),
]

gestion/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('reservar/', views.reservar, name='reservar'),
    path('inventario/', views.inventario, name='inventario'),
    path('scan-qr/', views.scan_qr, name='scan-qr'),
    path('capture-qr/', views.capture_qr, name='capture-qr'),
]

sistema/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Index.urls')),
    path('', include('gestion.urls')),
]

gestion/models.py
from django.db import models
from datetime import date, time, timedelta

TIPO_SERVICIO_CHOICES = (
        ('Grabacion', 'Grabación'),
        ('Entrega', 'Entrega'),
)

TIPO_IDENTIFICACION_CHOICES = (
        ('CC', 'C.C'),
        ('TI', 'T.I')
)

LUGAR_CHOICES = (
        ('1', 'Lugar 1'),
        ('2', 'Lugar 2'),
        ('3', 'Lugar 3'),
)

class Reserva(models.Model):

    nombre_completo = models.CharField(max_length=100)
    correo_institucional = models.EmailField()
    tipo_identificacion = models.CharField(max_length=50, choices=TIPO_IDENTIFICACION_CHOICES)
    numero_identificacion = models.CharField(max_length=50)
    fecha = models.DateField(default=date.today)
    hora = models.TimeField(default=time(hour=8, minute=0))
    tipo_servicio = models.CharField(max_length=20, choices=TIPO_SERVICIO_CHOICES)
    lugar_evento = models.CharField(max_length=50, blank=True, null=True, choices=LUGAR_CHOICES)
    lugar_grabacion = models.CharField(max_length=50, blank=True, null=True, choices=LUGAR_CHOICES)
    duracion_evento = models.DurationField(blank=True, null=True, default=timedelta(hours=1))
    lugar_origen = models.CharField(max_length=100, blank=True, null=True, choices=LUGAR_CHOICES)
    lugar_destino = models.CharField(max_length=100, blank=True, null=True, choices=LUGAR_CHOICES)
    medidas_paquete = models.CharField(max_length=50, blank=True, null=True)
    peso_paquete = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    correo_destinatario = models.EmailField(blank=True, null=True)

"""
Opciones de la tabla Devices (Dispositivos)
"""
ESTADO_CHOICES = (
    ('Disponible', 'Disponible'),
    ('No Disponible', 'No Disponible'),
    ('En mantenimiento', 'En mantenimiento'),
)

TIPO_CHOICES = (
    ('Robot', 'Robot'),
    ('Drone', 'Drone'),
    ('Sensor', 'Sensor'),
    ('Otro', 'Otro'),
)

class Devices(models.Model):
    dispositivo = models.CharField(
        verbose_name="Nombre del dispositivo", max_length=100,
        help_text="Ingrese el nombre del dispositivo",unique=True,
        ) 
    cantidad = models.IntegerField(
        verbose_name="Cantidad de dispositivos",
        help_text="Ingrese la cantidad de dispositivos disponibles",
        default=1,
        )
    estado = models.CharField(
        max_length=50, 
        verbose_name="Estado del dispositivo", 
        help_text="Seleccione el estado del dispositivo",
        choices=ESTADO_CHOICES,
        )
    tipo =  models.CharField(
        max_length=50,
        verbose_name="Tipo de dispositivo",
        choices=TIPO_CHOICES,
        help_text="Seleccione el tipo de dispositivo",
        )
    marca = models.CharField(
        max_length=100,
        verbose_name="Marca del dispositivo",
        blank=True,
        null=True,
        help_text="Ingrese la marca del dispositivo (opcional)",
        )
    def __str__(self):
        return self.dispositivo 

class Users(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    codigo = models.IntegerField(default=0)
    def __str__(self):
        return self.nombre

gestion/forms.py
from django import forms
from .models import Reserva

class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['nombre_completo', 'correo_institucional', 'tipo_identificacion', 'numero_identificacion', 'fecha', 'hora', 'tipo_servicio']

class GrabacionForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['lugar_evento', 'lugar_grabacion', 'duracion_evento']

class EntregaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['lugar_origen', 'lugar_destino', 'medidas_paquete', 'peso_paquete', 'correo_destinatario']

gestion/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.core.files.base import ContentFile
from .models import Devices, Users
from .forms import ReservaForm, GrabacionForm, EntregaForm
from pyzbar import pyzbar
import cv2
import qrcode
import os
from django.contrib.auth.decorators import login_required
import random
import string

@login_required
def reservar(request):
    if request.method == 'POST':
        reserva_form = ReservaForm(request.POST)
        grabacion_form = GrabacionForm(request.POST)
        entrega_form = EntregaForm(request.POST)

        if reserva_form.is_valid():
            reserva_instance = reserva_form.save(commit=False)
            tipo_servicio = reserva_instance.tipo_servicio
            data_to_encode = generate_random_code()
            qr_code = generate_qr_code(data_to_encode)
            if tipo_servicio == 'Grabacion' and grabacion_form.is_valid():
                reserva_instance.lugar_evento = grabacion_form.cleaned_data['lugar_evento']
                reserva_instance.lugar_grabacion = grabacion_form.cleaned_data['lugar_grabacion']
                reserva_instance.duracion_evento = grabacion_form.cleaned_data['duracion_evento']
                reserva_instance.save()
                message = 'A continuación, adjuntamos el código QR para que pueda descargar el video del evento (Video disponible al finalizar el evento):'
                enviar_qr(qr_code, message)
                return redirect('index')  # Redirigir a una página de éxito
            elif tipo_servicio == 'Entrega' and entrega_form.is_valid():
                reserva_instance.lugar_origen = entrega_form.cleaned_data['lugar_origen']
                reserva_instance.lugar_destino = entrega_form.cleaned_data['lugar_destino']
                reserva_instance.medidas_paquete = entrega_form.cleaned_data['medidas_paquete']
                reserva_instance.peso_paquete = entrega_form.cleaned_data['peso_paquete']
                reserva_instance.correo_destinatario = entrega_form.cleaned_data[
                    'correo_destinatario']
                reserva_instance.save()
                message = 'A continuación, adjuntamos el código QR para que pueda confirmar la entrega de su producto:'
                enviar_qr(qr_code, message)
                return redirect('index')  # Redirigir a una página de éxito
    else:
        reserva_form = ReservaForm()
        grabacion_form = GrabacionForm()
        entrega_form = EntregaForm()

    return render(request, 'reservar.html', {
        'reserva_form': reserva_form,
        'grabacion_form': grabacion_form,
        'entrega_form': entrega_form,
    })

def enviar_qr(qr_code, message):
    subject = 'Codigo QR confirmacion de reserva'
    template = render_to_string('email.html', {
        'message': message,
    })

    email_user = EmailMessage(
        subject,
        template,
        settings.EMAIL_HOST_USER,
        ['carloscamacho0602@gmail.com']
    )

    email_admin = EmailMessage(
        subject,
        template,
        settings.EMAIL_HOST_USER,
        ['sistema.gestion.drones@gmail.com']
    )

    email_user.fail_silently = False
    email_admin.fail_silently = False
    with open(qr_code, 'rb') as img:
        image = img.read()
        email_user.attach('qr_code.png', image, 'image/png')
        email_admin.attach('qr_code.png', image, 'image/png')
    email_user.send()
    email_admin.send()

def generate_qr_code(data, filename='qr_code.png'):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(data)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    img_path = os.path.join(settings.BASE_DIR, 'media', filename)
    img.save(img_path)
    return img_path

def generate_random_code(length=10):
    # Define el conjunto de caracteres: letras mayúsculas y números
    characters = string.ascii_uppercase + string.digits
    # Genera un código aleatorio
    random_code = ''.join(random.choice(characters) for _ in range(length))
    return random_code

@login_required
def inventario(request):
    devices = Devices.objects.all()
    if devices:
        return render(request, 'inventario.html', {
            'devices': devices,
        })
    else:
        return render(request, 'inventario.html', {
            'error': 'No hay dispositivos en el momento',
        })

@login_required
def scan_qr(request):
    return render(request, 'scan_qr.html')

@login_required
def capture_qr(request):
    barcodeData = None
    if request.method == 'POST':
        codigo = request.POST.get('codigo', '')
        user = Users.objects.filter(codigo=codigo)
        print(user)
        if user.exists():
            name = user[0].nombre
            messages.success(request, f'El usuario con codigo {codigo} es {name}')
            return redirect('reservar')
        else:
            messages.error(request, f'El usuario con codigo {codigo} no existe')
            return redirect('scan-qr')
    else:
        cap = cv2.VideoCapture(0)

        if not cap.isOpened():
            print("Error: Could not open camera.")
            return
        while cap.isOpened():
            ret, frame = cap.read()
            if ret:
                barcodes = pyzbar.decode(frame)
                for barcode in barcodes:
                    (x, y, w, h) = barcode.rect
                    cv2.rectangle(frame, (x, y), (x + w, y + h),
                                  (0, 0, 255), 2)
                    barcodeData = barcode.data.decode("utf-8")
                    barcodeType = barcode.type
                    text = "{} ({})".format(barcodeData, barcodeType)
                    cv2.putText(frame, text, (x, y - 10),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
                    print("Barcode: {} - Type: {}".format(barcodeData, barcodeType))

                cv2.imshow("Barcode Scanner", frame)
                if cv2.waitKey(25) & 0xFF == ord('q'):
                    cap.release()
                    cv2.destroyAllWindows()
                    break
            else:
                break
        return render(request, 'scan_qr.html', {'qr_result': barcodeData})

gestion/templates/agendar_reserva.html
{% block content %}

<div>
   <h1>Enviar QR</h1>
   <button type="submit" formmethod="POST">Enviar</button>
</div>

{% endblock %}

gestion/templates/email.html
{{message}}

gestion/templates/inventario.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
    {% if devices %}
    <div class="content">
        <div class="inventory">
            <p class="title"> Inventario </p>
            <table border="1" class = "styled-table">
                <thead>
                    <th>Dispositivo</th>
                    <th>Cantidad</th>
                    <th>Estado</th>
                    <th>Tipo</th>
                    <th>Marca</th>
                </thead>
                {% for device in devices %}
                <tbody>
                    <tr>
                    <td><p>{{device.dispositivo}}</p></td>
                    <td><p>{{device.cantidad}}</p></td>
                    <td><p>{{device.estado}}</p></td>
                    <td><p>{{device.tipo}}</p></td>
                    <td><p>{{device.marca}}</p></td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
    {% else %}
    <div class="content">
        <p class="title"> {{error}} </p>
    </div>
    {% endif %}
{% endblock %}

gestion/templates/reservar.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" type="text/css" href="../static/css/reservar.css">
<script>
    $(document).ready(function() {
        $('#id_tipo_servicio').change(function() {
            var tipoServicio = $(this).val();
            if (tipoServicio == 'Grabacion') {
                $('#grabacionFields').show();
                $('#entregaFields').hide();
            } else if (tipoServicio == 'Entrega') {
                $('#grabacionFields').hide();
                $('#entregaFields').show();
            }
        });
    });
</script>
<div class="content">
    <div class="container2">
        <h2>Formulario de Reserva</h2>
        <form method="post">
            {% csrf_token %}
            {{ reserva_form.as_p }}
            
            <div id="grabacionFields" style="display: none;">
                <h3>Detalles de Grabación</h3>
                {{ grabacion_form.as_p }}
            </div>
            
            <div id="entregaFields" style="display: none;">
                <h3>Detalles de Entrega</h3>
                {{ entrega_form.as_p }}
            </div>
            
            <input type="submit" value="Reservar">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %} style="color: white; list-style: none;">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

gestion/templates/scan_qr.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
    <div class="content">
      <div>
         {% if messages %}
            <ul class="messages">
               {% for message in messages %}
                  <li style="list-style: none;" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
               {% endfor %}
            </ul>
         {% endif %}
         <form action="{% url 'capture-qr' %}" method="GET">
            <h1>Escanear código de barras</h1>
            {% csrf_token %}
            <p style="text-align: center; margin-top: 15px;">
               <button type="submit">Escanear</button>
            </p>
         </form>
         <br>
         {% if qr_result %}
         <form method="POST">
               <h2>Código de estudiante:</h2>
               {% csrf_token %}
               <textarea style="margin-top: 10px;" rows="1" cols="11" name="codigo" readonly>{{qr_result}}</textarea>
               <p style="text-align: center; margin-top: 15px;">
                  <button type="submit">Validar</button>
               </p>
            </form>
         {% endif %}
      </div>
   </div>
{% endblock %}